---
title: "CarexhelodesSSR"
author: "Marcial Escudero"
date: "April 23, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r}
library(poppr)
mydata <- read.genalex ("mydata.csv")
mydata

mydata2 <- missingno(mydata, type = "genotype", cutoff = 0.60, quiet = FALSE, freq = FALSE)

mydata3 <- missingno(mydata, type = "genotype", cutoff = 0, quiet = FALSE, freq = FALSE)

mytree <- aboot(mydata2, tree = "nj", distance = "nei.dist", sample = 1000, 
                cutoff = 50, showtree = TRUE, missing = "mean", mcutoff = 0.6, 
                quiet = FALSE, root = NULL)

library(phytools)
mytree$node.label[is.na(mytree$node.label)] <- ""
mytree <- midpoint.root(mytree)

pdffn = paste0("nei_NJ.pdf")
pdf(file=pdffn, width=8, height=15)
plot(mytree, type = "phylogram", use.edge.length = TRUE,
     node.pos = NULL, show.tip.label = TRUE, show.node.label = T,
     edge.color = "black", edge.width = 1, edge.lty = 1, font = 0.3,
     cex = 0.4, adj = NULL, srt = 0, no.margin = FALSE,
     root.edge = FALSE, label.offset = 0, underscore = FALSE,
     x.lim = NULL, y.lim = NULL, direction = "rightwards",
     lab4ut = "horizontal", tip.color = "black")
dev.off()

test_replen(mydata2, c(2, 6, 6, 3, 4, 3, 2, 3, 3, 2, 3, 3, 6, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 4, 6, 2, 2, 2, 2, 2, 2, 2, 2))
new_replen <- fix_replen(mydata2, c(2, 6, 6, 3, 4, 3, 2, 3, 3, 2, 3, 3, 6, 2, 3, 2, 3, 2, 2, 2, 2, 2, 2, 2, 4, 6, 2, 2, 2, 2, 2, 2, 2, 2))

mytree2 <- bruvo.boot(mydata2, replen = new_replen , add = TRUE, loss = TRUE, sample = 1000, 
           tree = "nj", showtree = TRUE, cutoff = NULL, quiet = FALSE,
           root = NULL)

mytree2 <- midpoint.root(mytree2)
mytree2$node.label[as.numeric(mytree2$node.label) < 50 ] <- ""

pdffn = paste0("Bruvo_NJ.pdf")
pdf(file=pdffn, width=8, height=15)
plot(mytree2, type = "phylogram", use.edge.length = TRUE,
     node.pos = NULL, show.tip.label = TRUE, show.node.label = TRUE,
     edge.color = "black", edge.width = 1, edge.lty = 1, font = 0.3,
     cex = 0.4, adj = NULL, srt = 0, no.margin = FALSE,
     root.edge = FALSE, label.offset = 0, underscore = FALSE,
     x.lim = NULL, y.lim = NULL, direction = "rightwards",
     lab4ut = "horizontal", tip.color = "black")
dev.off()

bruvo.msn.mydata <- bruvo.msn(mydata2, replen = new_replen, add = TRUE, loss = TRUE,
  mlg.compute = "original", palette = topo.colors, sublist = "All",
  blacklist = NULL, vertex.label = "MLG", gscale = TRUE,
  glim = c(0, 0.8), gadj = 15, gweight = 2, wscale = TRUE,
  showplot = TRUE, include.ties = FALSE, threshold = NULL,
  clustering.algorithm = NULL)

pdffn = paste0("Bruvo_NET.pdf")
pdf(file=pdffn, width=8, height=8)
plot_poppr_msn(mydata2, bruvo.msn.mydata, gscale = T, gadj = 15,
               mlg.compute = "original", glim = c(0, 0.8), gweight = 1,
               wscale = T, nodelab = 2, inds = "",
               mlg = F, quantiles = TRUE, cutoff = NULL, palette = NULL, beforecut = FALSE, pop.leg = TRUE,
               scale.leg = TRUE)
dev.off()

pdffn = paste0("Bruvo_NET2.pdf")
pdf(file=pdffn, width=8, height=8)
plot_poppr_msn(mydata2, bruvo.msn.mydata, gadj = 15, inds = "none", beforecut = T, cutoff = 0.5)
dev.off()

write.table (private_alleles(mydata2, form = alleles ~ ., report = "table",
level = "population", count.alleles = TRUE, drop = FALSE), file = "private.alleles.txt")

write.table (poppr(mydata2), file = "diversityindices.txt")
write.table(locus_table(mydata2), file = "locitable.txt")

mean(summary(popsub(mydata2, "CHE1"))$Hobs)
mean(summary(popsub(mydata2, "CHE2"))$Hobs)
mean(summary(popsub(mydata2, "COR"))$Hobs)
mean(summary(popsub(mydata2, "MON"))$Hobs)
mean(summary(popsub(mydata2, "GUI"))$Hobs)
mean(summary(popsub(mydata2, "AZN1"))$Hobs)
mean(summary(popsub(mydata2, "AZN2"))$Hobs)


```


Making maps!

```{r}
devtools::install_github("dkahle/ggmap") 
devtools::install_github("tidyverse/ggplot2") 
library(ggplot2)
library(ggmap)

mydatamapa <- read.csv("mydata2.csv")

Madronalejo <- get_stamenmap(bbox = c(left = min(mydatamapa$lon)- 0.0001, bottom = min(mydatamapa$lat)- 0.0001, right = max(mydatamapa$lon) + 0.0001 , top = max(mydatamapa$lat)+ 0.0001), zoom = 10, maptype = c("terrain",
  "terrain-background", "terrain-labels", "terrain-lines", "toner",
  "toner-2010", "toner-2011", "toner-background", "toner-hybrid",
  "toner-labels", "toner-lines", "toner-lite", "watercolor"),
  crop = TRUE, messaging = FALSE, urlonly = FALSE,
  color = c("color", "bw"), force = FALSE, where = tempdir())

p <- ggmap(Madronalejo, extent = "panel", maprange = FALSE,
  legend = "right", padding = 0.02, darken = c(0, "black"), maptype = "terrain", scale = 2)
p + geom_point(data=mydatamapa[mydatamapa$Colour == "white",], aes(x=lon, y=lat), color="white", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "blue",], aes(x=lon, y=lat), color="blue", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "yellow",], aes(x=lon, y=lat), color="yellow", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "orange",], aes(x=lon, y=lat), color="orange", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "red",], aes(x=lon, y=lat), color="red", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "grey",], aes(x=lon, y=lat), color="pink", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "black",], aes(x=lon, y=lat), color="purple", size=1) + scale_color_manual(values = c("unknown" = "white", "2n = 68" = "yellow",  "2n = 68*" = "orange", "2n = 60*" = "red",  "2n = 70" = "blue", "2n = 70*" = "pink", "2n = 72" =  "purple")) + theme(legend.position = "right")

pdffn = paste0("mapa", ".version2.pdf")
pdf(file=pdffn, width=6, height=30)
p + geom_point(data=mydatamapa[mydatamapa$Colour == "white",], aes(x=lon, y=lat), color="white", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "blue",], aes(x=lon, y=lat), color="blue", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "yellow",], aes(x=lon, y=lat), color="yellow", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "orange",], aes(x=lon, y=lat), color="orange", size=1, alpha=0.5) + geom_point(data=mydatamapa[mydatamapa$Colour == "red",], aes(x=lon, y=lat), color="red", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "grey",], aes(x=lon, y=lat), color="pink", size=1) + geom_point(data=mydatamapa[mydatamapa$Colour == "black",], aes(x=lon, y=lat), color="purple", size=1) + scale_color_manual(values = c("unknown" = "white", "2n = 68" = "yellow",  "2n = 68*" = "orange", "2n = 60*" = "red",  "2n = 70" = "blue", "2n = 70*" = "pink", "2n = 72" =  "purple")) + theme(legend.position = "right")
dev.off()


plot.new()
legend(1, legend=c("unknown", "2n = 68", "2n = 68*", "2n = 69*", "2n = 70", "2n = 70*", "2n = 72"), col=c("white", "yellow", "orange", "red", "blue", "pink", "purple"))


Madronalejo <- get_map(bbox = c(left = min(mydatamapa$lon)+ 0.0001, bottom = min(mydatamapa$lat)+ 0.0001, right = max(mydatamapa$lon) + 0.0001 , top = max(mydatamapa$lat)+ 0.0001),
  zoom = "auto", scale = "auto", maptype = "satellite", source = c("google", "osm", "stamen"),
  force = ifelse(source == "google", TRUE, FALSE), messaging = FALSE,
  urlonly = FALSE, filename = NULL, crop = TRUE, color = c("color",
  "bw"), language = "en-EN")

```


```{r}

library(ggplot2)
library(ggmap)
latitudes <- c(35.08, 35.10, 37.23, 37.05, 37.50, 37.58, 37.59)
longitudes <- c(-5.37, -5.33, -7.95, -8.52, -6.59, -6.25, -6.36)
populations <- c("CHE1", "CHE2", "COR", "MON", "GUI", "AZN1", "AZN2")
mapping <- cbind(populations, latitudes, longitudes)

p <- ggmap(get_googlemap(center = c(lon = 7.5, lat = 36.5),
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))

p + geom_point(aes(x = Longitude, y = Latitude,  colour = Initial.Type.Group), data = i2, size = 0.5) + 
  theme(legend.position="bottom")

p + geom_point(aes(x = Longitude, y = Latitude), colour = col1, data = i2, alpha=0.25, size = 0.5) + 
  theme(legend.position="bottom")  +
  geom_point(aes(x = x, y = y, stroke = 2), colour=col4, data = n, size =2.5) + 
  geom_label_repel(
    aes(x, y, label = label),
    data=n,
    family = 'Times', 
    size = 4, 
    box.padding = 0.2, point.padding = 0.3,
    segment.color = 'grey50') 
```

